rm -rf transcript
rm -rf work
rm -rf *.wlf
rm -rf modelsim.ini
rm -rf *.log
rm -rf verdilog
rm -rf vfastlog
rm -rf novas.rc
rm -rf *.vcd
rm -rf *.fsdb
rm -rf VerdiLog
rm -rf simv.*
rm -rf simv
rm -rf csrc
rm -rf ucli.key
rm -rf .vcsmx*